Folder path for pages needs to be quoted in additional single quotes
Without that change, the script will display the following error:

Dataview: Failed to execute view 'Main/NotesList/view.js'.

Error: Failed to parse query in 'pagePaths': Error: 
-- PARSING FAILED --------------------------------------------------

> 1 | Notes/Theology
    | ^

Expected one of the following: 

'!', '(', '-', 'csv(', 'outgoing(', file link, string, tag ('#hello/stuff')